name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my first actions jpb" 
        - name: list fiels
          run: ls
        - name: read files
          run: cat README.md       

